### ISSUE TITLE
[Better way?] Instead of writing the whole dotman script why not use just git?

### ISSUE THREAD

**Issue by kalkayan** [Bhupesh-V/dotman#20]
Atlassian has shown an amazing (possibly the best yet) way to store and share the dotfiles just using git, no wrapper needed. The trick is to use a `--bare` repository. 

The dotman script doesn't extend to multiple surface machines - i.e., if you have configured you dotfiles for ubuntu then how that work on macos? or windows? (there should be some sort of sharing of the files with branching).

Extend the idea like this - [https://github.com/kalkayan/dotfiles](https://github.com/kalkayan/dotfiles) and you have a `dotman` without any script and `chmod +x` (which was the headline of the this repository.

**Comment by Bhupesh-V** [comment]
@kalkayan thanks a lot for sharing this
So from what I have, understood is the mentioned approach can be good for collaborative (team-wise) dev in dotfiles but since a lot of users maintain & use their own dotifles, I still don't see a perfect use case for that.

> The dotman script doesn't extend to multiple surface machines - i.e., if you have configured you dotfiles for ubuntu then how that work on macos? or windows? (there should be some sort of sharing of the files with branching).

This is something I can agree on & haven't thought about how this could work. dotman's primary goal is to automate the simple task of `diff`ing and copying the changed dotfiles back and forth

I am closing this one, for now, if you have any other thoughts do let me know :)
